[package]
edition = "2024"
name = "brusbee"
rust-version = "1.88"
version = "0.1.0"

[[bin]]
name = "brusbee"
path = "./src/bin/main.rs"

[dependencies]
critical-section = "1"
edge-dhcp = "0.7.0"
edge-nal = "0.6.0"
edge-nal-embassy = "0.8.1"
embassy-executor = "0.10.0"
embassy-net = { version = "0.8.0", features = [ # TODO: update to 0.9 once edge-nal allows
  "dhcpv4",
  "medium-ethernet",
  "tcp",
  "udp",
] }
embassy-time = "0.5.0"
embedded-hal-bus = "0.3.0"
embedded-io-async = "0.7"
embedded-sdmmc = "0.10.0"
esp-alloc = "0.10.0"
esp-backtrace = { version = "0.19.0", features = ["panic-handler", "println"] }
esp-bootloader-esp-idf = "0.5.0"
esp-hal = { version = "1.1.2", features = ["log-04", "unstable"] }
esp-println = { version = "0.17.0", features = ["log-04"] }
esp-rtos = { version = "0.3.0", features = ["esp-radio", "embassy", "log-04"] }
esp-radio = { version = "1.0.0-beta.0", features = [
  "log-04",
  "wifi",
  "sniffer",
  "unstable",
] }
ieee80211 = { version = "0.4.0", default-features = false }
log = "0.4.27"
picoserve = { version = "0.18.0", features = ["embassy"] }
static_cell = "2.1.0"

[features]
default = ["esp32c5"]
esp32c5 = [
  "esp-backtrace/esp32c5",
  "esp-bootloader-esp-idf/esp32c5",
  "esp-hal/esp32c5",
  "esp-rtos/esp32c5",
  "esp-radio/esp32c5",
]

# For fine tuning these settings, please refer to https://doc.rust-lang.org/cargo/reference/profiles.html
[profile.dev]
# The default debug profile is too slow and too big for resource-constrained devices.
# Always build with some optimizations enabled.
opt-level = "s"

[profile.release]
codegen-units = 1 # LLVM can perform better optimizations using a single thread
debug = 2         # prefer slower builds but better debugging experience
lto = 'fat'
opt-level = 's'
